server:
  port: 5677
spring:
  application:
    name: cloud-mall-chat
  #zipkin服务所在地址
  zipkin:
    base-url: http://localhost:9411/
  #配置采样百分比,开发环境可以设置为1，表示全部，生产就用默认
  sleuth:
    sampler:
      probability: 1
  #配置springBoot admin
  boot:
    admin:
      client:
        url:  http://localhost:8921   #这里配置admin server 的地址
        username: root
        password: 18420163207
  thymeleaf:
    cache: false    #关闭thymeleaf的缓存
  redis:
    port: 6379
    password:
    host: localhost
    database: 10
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_mall_user?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: 18420163207
    driver-class-name: com.mysql.jdbc.Driver
  #  rabbitmq
  rabbitmq:
    username: guest
    virtual-host: /ems
    password: guest
    host: localhost
    #springcloud配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848    #单机部署
    sentinel:
      transport:
        port: 8720
        dashboard: localhost:8080
    #配置seata
    alibaba:
      seata:
        tx-service-group: my_test_tx_group

  main:
    allow-bean-definition-overriding: true    #不然多个feign接口连接相同的微服务则会报错

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true



#设置ribbon的超时时间
ribbon:
  ReadTimeout: 8000
  ConnectTimeout: 8000


#自定义扫描包
scan:
  packageName: com.boot.controller

#feign日志增强
logging:
  level:
    com.boot.controller.SearchController: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"

#gitee 第三方配置
gitee:
  oauth:
    CLIENTID: e3c40923721dcdcb71580dcc4f037cf7cc9d91dc4be91c6b10afb85b1f3bb755
    CLIENTSECRET: 1f264ab539a3607c325c93e61c685cc492b9d29ccd31cab6c624225d05a91219
    callback: http://localhost/gitee/callback


#配置表情插件
cloud:
  emoji:
    emojiMap:
      {
        /emoji-E01: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-a-bizuigangabiaoqingxiaolian'></use></svg>,
        /emoji-E02: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-a-gangaliuhanbiaoqingxiaolian'></use></svg>,
        /emoji-E03: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-a-baochitaiduobiaoqingxiaolian'></use></svg>,
        /emoji-E04: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-a-keaiyouqudeganxingqubiaoqingxiaolian'></use></svg>,
        /emoji-E05: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-a-dakubeishangshangxinbiaoqingxiaolian'></use></svg>,
        /emoji-E06: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-a-bucuohaochiweidaobiaoqingxiaolian'></use></svg>,
        /emoji-E07: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-a-aixihuanliukoushuisebiaoqingxiaolian'></use></svg>,
        /emoji-E08: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-a-eabukenengbiaoqingxiaolian'></use></svg>,
        /emoji-E09: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-a-aimujingpeijingyangwasejingyabiaoqingxiaolian'></use></svg>,
        /emoji-E10: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-a-nulifendoujiayoubiaoqingxiaolian'></use></svg>,
        /emoji-E11: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-a-kuxiaobudegangaxingqiubiaoqing'></use></svg>,
        /emoji-E12: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-a-xiaolianbiaoqing'></use></svg>,
        /emoji-E13: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-a-gaoxinghaoxinqingbiaoqingxihuanbiaoqingxiaolian'></use></svg>,
        /emoji-E14: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-a-kuzhuangkushuaiqishuashuaibiaoqingxiaolian'></use></svg>,
        /emoji-E16: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-zhuangkeai'></use></svg>,
        /emoji-E17: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-a-shengqifennumaohuofenkaiqifenbiaoqingxiaolian'></use></svg>,
        /emoji-E18: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-a-jingyajingqiwasetianlabiaoqingxiaolian'></use></svg>,
        /emoji-E19: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-a-taibanglejingyabangbangdebiaoqingxiaolian'></use></svg>,
        /emoji-E20: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-a-aiqingxihuansebiaoqingxiaolian'></use></svg>,
        /emoji-E21: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-lenghan'></use></svg>,
        /emoji-E22: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-baiyan'></use></svg>,
        /emoji-E23: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-tiaopi'></use></svg>,
        /emoji-E24: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-fanu'></use></svg>,
        /emoji-E25: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-kun'></use></svg>,
        /emoji-E26: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-leiku'></use></svg>,
        /emoji-E27: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-kaixin'></use></svg>,
        /emoji-E28: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-weixiao'></use></svg>,
        /emoji-E29: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-yiwen'></use></svg>,
        /emoji-E30: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-shetou'></use></svg>,
        /emoji-E31: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-daxiao'></use></svg>,
        /emoji-E32: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-jingya'></use></svg>,
        /emoji-E33: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-jingxia'></use></svg>,
        /emoji-E34: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-shiwang'></use></svg>,
        /emoji-E35: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-wuliao'></use></svg>,
        /emoji-E36: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-juezui'></use></svg>,
        /emoji-E37: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-jiyan'></use></svg>,
        /emoji-E38: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-dai'></use></svg>,
        /emoji-E39: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-liulei'></use></svg>,
        /emoji-E40: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-yun'></use></svg>,
        /emoji-E41: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-se'></use></svg>,
        /emoji-E42: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-tu'></use></svg>,
        /emoji-E43: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-kouzhao'></use></svg>,
        /emoji-E44: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-mowang'></use></svg>,
        /emoji-E45: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-shuijue'></use></svg>,
        /emoji-E46: <svg class='icon' aria-hidden='true'><use xlink:href='#icon-ku'></use></svg>
      }
