server:
  port: 93
spring:
  application:
    name: cloud-mall-admin
  #zipkin服务所在地址
  zipkin:
    base-url: http://localhost:9411/
  #配置采样百分比,开发环境可以设置为1，表示全部，生产就用默认
  sleuth:
    sampler:
      probability: 1
  #配置springBoot admin
  boot:
    admin:
      client:
        url:  http://localhost:8921   #这里配置admin server 的地址
        username: root
        password: 18420163207
  thymeleaf:
    cache: false    #关闭thymeleaf的缓存
  redis:
    port: 6379
    password:
    host: localhost
    database: 10
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_mall_user?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: 18420163207
    driver-class-name: com.mysql.jdbc.Driver
  #  rabbitmq
  rabbitmq:
    username: guest
    virtual-host: /ems
    password: guest
    host: localhost
    #springcloud配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848    #单机部署
    sentinel:
      transport:
        port: 8720
        dashboard: localhost:8080
    #配置seata
    alibaba:
      seata:
        tx-service-group: my_test_tx_group

  main:
    allow-bean-definition-overriding: true    #不然多个feign接口连接相同的微服务则会报错

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true



#设置ribbon的超时时间
ribbon:
  ReadTimeout: 8000
  ConnectTimeout: 8000


#自定义扫描包
scan:
  packageName: com.boot.controller

#feign日志增强
logging:
  level:
    com.boot.controller.SearchController: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"

#gitee 第三方配置
gitee:
  oauth:
    CLIENTID: e3c40923721dcdcb71580dcc4f037cf7cc9d91dc4be91c6b10afb85b1f3bb755
    CLIENTSECRET: 1f264ab539a3607c325c93e61c685cc492b9d29ccd31cab6c624225d05a91219
    callback: http://localhost/gitee/callback

fdfs:
  soTimeout: 1500
  connectTimeout: 600
  trackerList: 192.168.184.132:22122  #tracker路径，TrackerList参数,支持多个
